In [8]:
from keras.preprocessing.text import one_hot
from keras.layers import Embedding
from keras.models import Sequential
from keras.preprocessing.sequence import pad_sequences

In [3]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
 ]

In [4]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer']

In [5]:
voc_size = 10000

In [6]:
onehot_representation =[one_hot(word, voc_size) for word in sent]
print(onehot_representation)

[[3047, 8934, 4405, 6110], [3047, 8934, 4405, 2116], [3047, 3338, 4405, 4183], [6547, 7390, 3678, 7633, 2848], [6547, 7390, 3678, 7633, 9703]]


In [9]:
import numpy as np


In [11]:
sent_lenght =8
embedded_docs =pad_sequences(onehot_representation, padding='pre', maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 3047 8934 4405 6110]
 [   0    0    0    0 3047 8934 4405 2116]
 [   0    0    0    0 3047 3338 4405 4183]
 [   0    0    0 6547 7390 3678 7633 2848]
 [   0    0    0 6547 7390 3678 7633 9703]]


In [12]:
model = Sequential()

model.add(Embedding(voc_size, 10, input_length=sent_lenght))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

array([[[-1.59187093e-02,  2.52725743e-02,  7.68930838e-03,
         -2.19717380e-02, -1.53280385e-02,  3.89200561e-02,
          1.51369236e-02, -2.73038503e-02, -3.08370944e-02,
         -4.30568941e-02],
        [-1.59187093e-02,  2.52725743e-02,  7.68930838e-03,
         -2.19717380e-02, -1.53280385e-02,  3.89200561e-02,
          1.51369236e-02, -2.73038503e-02, -3.08370944e-02,
         -4.30568941e-02],
        [-1.59187093e-02,  2.52725743e-02,  7.68930838e-03,
         -2.19717380e-02, -1.53280385e-02,  3.89200561e-02,
          1.51369236e-02, -2.73038503e-02, -3.08370944e-02,
         -4.30568941e-02],
        [-1.59187093e-02,  2.52725743e-02,  7.68930838e-03,
         -2.19717380e-02, -1.53280385e-02,  3.89200561e-02,
          1.51369236e-02, -2.73038503e-02, -3.08370944e-02,
         -4.30568941e-02],
        [-3.19442637e-02,  2.10996903e-02, -2.52529271e-02,
          5.86094707e-03,  4.25687917e-02, -4.16284911e-02,
         -3.94324884e-02,  3.45830359e-02,  5.459643